services:
  - type: web
    name: telegram_bot2
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
